
export const FETCH_BANK_DATA = 'FETCH_BANK_DATA';
export const FETCH_BANK_DATA_FULFILLED = 'FETCH_BANK_DATA_FULFILLED';
export const SELECTED_BANK_DATA = 'SELECTED_BANK_DATA';

export const FETCH_BANK_ACCOUNT_DATA = 'FETCH_BANK_ACCOUNT_DATA';
export const FETCH_BANK_ACCOUNT_DATA_FULFILLED = 'FETCH_BANK_ACCOUNT_DATA_FULFILLED';
export const SELECTED_BANK_ACCOUNT_DATA = 'SELECTED_BANK_ACCOUNT_DATA';

export const FETCH_BANK_BALANCE = 'FETCH_BANK_BALANCE';
export const FETCH_BANK_BALANCE_FULFILLED = 'FETCH_BANK_BALANCE_FULFILLED';

export const FETCH_INCOME_DATA = 'FETCH_INCOME_DATA';
export const FETCH_INCOME_DATA_FULFILLED = 'FETCH_INCOME_DATA_FULFILLED';

export const FETCH_SPENDING = 'FETCH_SPENDING';
export const FETCH_SPENDING_FULFILLED = 'FETCH_SPENDING_FULFILLED';

export const FETCH_USER_DATA = 'FETCH_USER_DATA';
export const FETCH_USER_DATA_FULFILLED = 'FETCH_USER_DATA_FULFILLED';

export const FETCH_BILL_MONITOR = 'FETCH_BILL_MONITOR';
export const FETCH_BILL_MONITOR_FULFILLED = 'FETCH_BILL_MONITOR_FULFILLED';
